### ISSUE TITLE
When canvas on camera, the material is wrong

### ISSUE THREAD

**Issue by LawrenceHan** [all-iver/shapes2d#1]
You put a button on canvas, the set canvas overlay camera, then you can see the problem.

**Comment by all-iver** [comment]
Coincidentally I just pushed some code that tries to fix this, check out the screen_space_camera branch and let me know if it works for you.  Unfortunately there's still something screwed up when you convert to sprite, but a possible workaround is to switch the canvas to overlay, convert to sprite, and then switch it back.

**Comment by LawrenceHan** [comment]
@all-iver I've already forked and merged your code. For convert to sprite can you point out a place that I can look at?

**Comment by all-iver** [comment]
@LawrenceHan I think I found a fix - check out my latest commit to that branch.

**Comment by LawrenceHan** [comment]
Thanks
