### ISSUE TITLE
bugs when rendering shapes on Screen Space Canvas (HDRP)

### ISSUE THREAD

**Issue by rimgro** [all-iver/shapes2d#20]
when i place shapes on screen space canvas, it looks wrong.
![image](https://user-images.githubusercontent.com/40323120/202970149-4405efb6-8db7-46d7-8e9f-3b6c8c14bbfa.png)
shapes have kind of transparency, but alpha of colors is 100, and when i changing alpha in Canvas Group, shapes starting look very strange

all this bug s disappering when i convert shapes to png
![image](https://user-images.githubusercontent.com/40323120/202970217-f12b53cd-593d-4a6e-9943-cef423eadc5f.png)
![image](https://user-images.githubusercontent.com/40323120/202970227-0e8609db-cd63-4cdd-b059-cf18cb7d6076.png)

**Comment by all-iver** [comment]
The user said in discord that this is something on their end to do with Graphics Compositor, so I'm closing this one.
